
include:
  - board: akdk_bt1
    shield: ortho_4row_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: akdk_bt1
    shield: ortho_4row_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: akdk_bt1
    shield: settings_reset
